version: '3'
name: snoospoof
services:
  api:
    build: .
    secrets:
      - praw.ini
    environment:
      SNOOSPOOF_API_PORT: $SNOOSPOOF_API_PORT
      SNOOSPOOF_API_HOST: $SNOOSPOOF_API_HOST
    ports:
     - "${SNOOSPOOF_API_PORT}:${SNOOSPOOF_API_PORT}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped:5

secrets:
  praw.ini:
    file: ./praw.ini